services:
  bashdoard:
    container_name: bashdoard
    environment:
      - BSHDRD_HOSTNAME=localhost
      - BSHDRD_THEME=random
      - BSHDRD_TITLE=BSHDRD
    image: ghcr.io/dchesbro/bashdoard:main
    ports:
      - 3000:3000
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
